# Generated by Django 4.2.1 on 2023-06-04 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_singup',
            old_name='is_number_validate',
            new_name='is_otp_validate',
        ),
    ]
